customhost = "database-1.ciubj8lplmcu.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ngsingyu-employee1"
customregion = "us-east-1"
